nohup: ignoring input
/home/xiao/miniconda3/envs/torch/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/xiao/miniconda3/envs/torch/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  warn(f"Failed to load image Python extension: {e}")
[epoch:0] loss 0.6349593438208103 acc 0.6611328125
[epoch:0] test loss 0.6711518934794835 test acc 0.6607142857142857
> /home/xiao/code/CS5242/CS5242/main.py(86)train()
-> for epoch in range(config["epoch"]):
(Pdb) Traceback (most recent call last):
  File "/home/xiao/code/CS5242/CS5242/main.py", line 148, in <module>
    net=train(net,trainloader,testloader)
  File "/home/xiao/code/CS5242/CS5242/main.py", line 86, in train
    for epoch in range(config["epoch"]):
  File "/home/xiao/code/CS5242/CS5242/main.py", line 86, in train
    for epoch in range(config["epoch"]):
  File "/home/xiao/miniconda3/envs/torch/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/xiao/miniconda3/envs/torch/lib/python3.10/bdb.py", line 114, in dispatch_line
    self.user_line(frame)
  File "/home/xiao/miniconda3/envs/torch/lib/python3.10/pdb.py", line 262, in user_line
    self.interaction(frame, None)
  File "/home/xiao/miniconda3/envs/torch/lib/python3.10/pdb.py", line 357, in interaction
    self._cmdloop()
  File "/home/xiao/miniconda3/envs/torch/lib/python3.10/pdb.py", line 322, in _cmdloop
    self.cmdloop()
  File "/home/xiao/miniconda3/envs/torch/lib/python3.10/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
OSError: [Errno 9] Bad file descriptor
